import { Product, Review, QuizQuestion } from './types';

export const COLLECTIONS = [
  {
    id: 'privee',
    name: 'La Collection Privée',
    description: 'Symphonies of rare extraits and absolute essences, meticulously crafted for the discerning connoisseur.',
    emoji: '🌹'
  },
  {
    id: 'jeunesse',
    name: 'L’Élixir de Jeunesse',
    description: 'Advanced cellular repair infusing gold-standard botanicals for timeless, radiant longevity.',
    emoji: '🧴'
  },
  {
    id: 'rituel',
    name: 'Le Rituel Purifiant',
    description: 'Gentle, oxygenating botanical waters and milk cleansers to restore the skin’s sacred natural barrier.',
    emoji: '🫧'
  }
];

export const PRODUCTS: Product[] = [
  // --- Category 1: Perfumes (perfumes) ---
  {
    id: 'rose-elegante',
    name: 'Rose Élégante Eau de Parfum',
    tagline: 'A romantic floral sanctuary captured in Damascus rose and soft musk.',
    category: 'perfumes',
    emoji: '🌸',
    price: 185,
    volume: '50 ml ℮ 1.7 FL. OZ.',
    concentration: 'Eau de Parfum',
    description: 'Maison Élise’s premier romantic creation. Rose Élégante is a delicate symphony celebrating Damascus rose, powdery peony, and warm white musk. Light yet remarkably persistent, it wraps the wearer in an elegant, sophisticated floral embrace.',
    ingredients: ['Alcohol Denat.', 'Parfum (Fragrance)', 'Aqua (Water)', 'Rosa Damascena Flower Oil', 'Limonene', 'Linalool', 'Citronellol', 'Geraniol'],
    olfactoryNotes: {
      top: 'Damascus Rose, Crisp Lychee, Pink Pepper',
      heart: 'Peony, Centifolia Rose, Magnolia blossom',
      base: 'White Musk, Warm Amber, Virginian Cedar'
    },
    applicationRitual: 'Mist lightly over warm pulse points: the neck, inner wrists, and behind the knees.',
    rating: 4.9,
    reviewsCount: 112,
    isBestSeller: true,
    collection: 'La Collection Privée',
    badge: 'Best Seller'
  },
  {
    id: 'velvet-bloom',
    name: 'Velvet Bloom Eau de Parfum',
    tagline: 'Soft jasmine, vanilla orchid and creamy warm sandalwood.',
    category: 'perfumes',
    emoji: '💐',
    price: 240,
    volume: '100 ml ℮ 3.4 FL. OZ.',
    concentration: 'Eau de Parfum',
    description: 'An elegant, creamy and velvety floral masterpiece. Velvet Bloom features rich star jasmine, exotic vanilla orchid, and Mysore sandalwood, delivering a beautiful, smooth trail that radiates confidence and subtle luxury.',
    ingredients: ['Alcohol Denat.', 'Parfum (Fragrance)', 'Aqua (Water)', 'Santalum Album Wood Oil', 'Benzyl Salicylate', 'Limonene', 'Linalool'],
    olfactoryNotes: {
      top: 'Star Jasmine, White Peach, Bergamot',
      heart: 'Vanilla Orchid, Heliotrope, Iris Root',
      base: 'Mysore Sandalwood, Warm Amber, Soft Musk'
    },
    applicationRitual: 'Apply onto hydrated skin to prolong the majestic trail.',
    rating: 4.8,
    reviewsCount: 88,
    isNew: true,
    collection: 'La Collection Privée',
    badge: 'New'
  },
  {
    id: 'midnight-petals',
    name: 'Midnight Petals Perfume',
    tagline: 'A sophisticated, mysterious blend of black rose, amber and cedar.',
    category: 'perfumes',
    emoji: '🥀',
    price: 290,
    volume: '75 ml ℮ 2.5 FL. OZ.',
    concentration: 'Extrait de Parfum',
    description: 'An opulent, night-blooming creation. Midnight Petals blends velvety black rose petals, warm fossilized amber, and smoky Atlas cedarwood. A magnetic, mysterious fragrance for the ultimate luxurious evening experience.',
    ingredients: ['Alcohol Denat.', 'Parfum (Fragrance)', 'Aqua (Water)', 'Eugenol', 'Farnesol', 'Limonene', 'Benzyl Benzoate'],
    olfactoryNotes: {
      top: 'Saffron, Pink Pepper, Black Cherry',
      heart: 'Black Rose, Absolute Jasmine, Leather Accord',
      base: 'Fossilized Amber, Atlas Cedar, Indonesian Patchouli'
    },
    applicationRitual: 'Mist generous clouds above your head and walk through the perfume shower.',
    rating: 5.0,
    reviewsCount: 94,
    collection: 'La Collection Privée',
    badge: 'Exclusive'
  },
  {
    id: 'santal-precieux',
    name: 'Santal Précieux Extrait',
    tagline: 'A heavy, luxurious cloud of Mysore sandalwood and warm cardamom.',
    category: 'perfumes',
    emoji: '🪵',
    price: 275,
    volume: '50 ml ℮ 1.7 FL. OZ.',
    concentration: 'Extrait de Parfum',
    description: 'A creamy, precious formulation celebrating the golden heritage of Mysore sandalwood. Infused with warm cardamom, sweet amber wood, and soft cashmere musk, Santal Précieux is exceptionally sophisticated.',
    ingredients: ['Alcohol Denat.', 'Parfum', 'Aqua', 'Santalum Album Oil', 'Cardamom Extract', 'Coumarin'],
    olfactoryNotes: {
      top: 'Cardamom, Violet Leaves, Papyrus',
      heart: 'Mysore Sandalwood, Virginia Cedarwood, Iris Powder',
      base: 'Warm Amber, Cashmere Musk, Leatherwood'
    },
    applicationRitual: 'Apply directly to warm pulse points. Allow to settle without rubbing.',
    rating: 4.9,
    reviewsCount: 67,
    collection: 'La Collection Privée'
  },
  {
    id: 'jasmin-imperial',
    name: 'Jasmin Impérial Eau de Parfum',
    tagline: 'Imperial absolute jasmine balanced with sparkling bergamot.',
    category: 'perfumes',
    emoji: '🌼',
    price: 195,
    volume: '50 ml ℮ 1.7 FL. OZ.',
    concentration: 'Eau de Parfum',
    description: 'A brilliant, solar tribute to the royal jasmine blossom. Jasmin Impérial marries absolute Sambac jasmine with sun-drenched Italian bergamot, fresh green tea leaves, and a soft, powdery white amber baseline.',
    ingredients: ['Alcohol Denat.', 'Parfum', 'Aqua', 'Jasminum Sambac Flower Oil', 'Linalool', 'Citral'],
    olfactoryNotes: {
      top: 'Italian Bergamot, Green Tea, Neroli',
      heart: 'Sambac Jasmine, Orange Blossom, Dewy Freesia',
      base: 'White Amber, Creamy Musk, Soft Benzoin'
    },
    applicationRitual: 'Mist lightly on collarbones and shoulders to envelope yourself in light.',
    rating: 4.7,
    reviewsCount: 42,
    collection: 'La Collection Privée'
  },

  // --- Category 2: Daily Moisturizers (daily-moisturizers) ---
  {
    id: 'silk-glow',
    name: 'Silk Glow Moisturizer',
    tagline: 'Daily weightless hydration infused with protective botanical extracts.',
    category: 'daily-moisturizers',
    emoji: '🧴',
    price: 95,
    volume: '50 ml ℮ 1.7 FL. OZ.',
    concentration: 'Daily Moisturizer',
    description: 'A luxurious cream that mimics the soft, light-reflective surface of natural silk. Infused with hydrolyzed silk proteins, squalane, and premium white tea extracts, Silk Glow deeply hydrates, refines skin texture, and creates an exquisite barrier.',
    ingredients: ['Aqua', 'Squalane', 'Glycerin', 'Hydrolyzed Silk', 'Camellia Sinensis Leaf Extract', 'Sodium Hyaluronate', 'Panthenol'],
    skinConcerns: ['hydration', 'radiance', 'smoothness'],
    applicationRitual: 'Press into clean face, neck, and décolleté using smooth, uplifting sweep motions every morning.',
    rating: 4.9,
    reviewsCount: 215,
    isBestSeller: true,
    collection: 'L’Élixir de Jeunesse',
    badge: 'Best Seller'
  },
  {
    id: 'hydre-satin-fluid',
    name: 'Hydre-Satin Fluid',
    tagline: 'Ultra-light fluid offering continuous moisture with rosewater.',
    category: 'daily-moisturizers',
    emoji: '💧',
    price: 85,
    volume: '50 ml ℮ 1.7 FL. OZ.',
    concentration: 'Lightweight Moisturizer',
    description: 'This ultra-light fluid melts instantly into the skin. Formulated with organic French rosewater, mountain cucumber extracts, and natural hyaluronic acid to lock in intense moisture without weight.',
    ingredients: ['Aqua', 'Rosa Damascena Flower Water', 'Aloe Barbadensis Leaf Juice', 'Cucumber Extract', 'Squalane'],
    skinConcerns: ['oil balance', 'dehydration'],
    applicationRitual: 'Smooth over face and neck in the morning. Follow with SPF.',
    rating: 4.7,
    reviewsCount: 104,
    collection: 'L’Élixir de Jeunesse'
  },
  {
    id: 'velvet-skin-cream',
    name: 'Velvet Skin Cream',
    tagline: 'Comforting, rich moisturizer crafted with ceramides and white tea.',
    category: 'daily-moisturizers',
    emoji: '🥛',
    price: 120,
    volume: '60 ml ℮ 2.0 FL. OZ.',
    concentration: 'Rich Face Cream',
    description: 'A deeply comforting, rich moisturizer crafted for dry or dehydrated skin. Fortified with botanical ceramides, unrefined African shea butter, and precious white camellia seed oil, it restores skin elasticity and velvety smoothness.',
    ingredients: ['Aqua', 'Squalane', 'Butyrospermum Parkii Butter', 'Camellia Japonica Seed Oil', 'Ceramide NP', 'Niacinamide'],
    skinConcerns: ['dryness', 'barrier repair', 'nourishment'],
    applicationRitual: 'Warm the rich cream between fingertips to activate. Press firmly into skin morning and night.',
    rating: 4.8,
    reviewsCount: 132,
    collection: 'L’Élixir de Jeunesse'
  },
  {
    id: 'ceramide-barrier-lotion',
    name: 'Ceramide Barrier Lotion',
    tagline: 'Fortifying daily lotion supporting the skin’s delicate lipid barrier.',
    category: 'daily-moisturizers',
    emoji: '🐚',
    price: 110,
    volume: '50 ml ℮ 1.7 FL. OZ.',
    concentration: 'Fortifying Lotion',
    description: 'An advanced lipid-replenishing fluid containing a golden ratio of skin-identical ceramides, cholesterol, and fatty acids. It reconstructs the skin barrier, reduces redness, and defends against external aggressors.',
    ingredients: ['Aqua', 'Ceramide EOP', 'Ceramide AP', 'Cholesterol', 'Phytosphingosine', 'Glycerin', 'Squalane'],
    skinConcerns: ['barrier repair', 'sensitivity', 'redness'],
    applicationRitual: 'Massage 1-2 pumps onto clean, dry skin after your serum.',
    rating: 4.8,
    reviewsCount: 59,
    collection: 'L’Élixir de Jeunesse'
  },
  {
    id: 'luminous-emulsion',
    name: 'Luminous Essence Emulsion',
    tagline: 'A lightweight essence-in-emulsion to restore brilliant, even tone.',
    category: 'daily-moisturizers',
    emoji: '⚡',
    price: 130,
    volume: '50 ml ℮ 1.7 FL. OZ.',
    concentration: 'Brightening Emulsion',
    description: 'Formulated to target dullness and uneven pigmentation. This silky emulsion features stable vitamin C, niacinamide, and licorice root extract to restore a radiant, crystal-clear, glowy complexion.',
    ingredients: ['Aqua', 'Niacinamide', '3-O-Ethyl Ascorbic Acid', 'Glycyrrhiza Glabra Root Extract', 'Tocopheryl Acetate'],
    skinConcerns: ['dullness', 'pigmentation', 'radiance'],
    applicationRitual: 'Smooth evenly over your face as your daily moisture step.',
    rating: 4.9,
    reviewsCount: 77,
    collection: 'L’Élixir de Jeunesse'
  },

  // --- Category 3: Night Creams (night-creams) ---
  {
    id: 'midnight-renewal',
    name: 'Midnight Renewal Cream',
    tagline: 'Deep overnight cellular repair formulated with active multi-peptides.',
    category: 'night-creams',
    emoji: '🌙',
    price: 180,
    volume: '50 ml ℮ 1.7 FL. OZ.',
    concentration: 'Active Night Repair',
    description: 'An elite overnight cellular therapy. This decadent cream combines active peptides, resveratrol, and squalane to stimulate natural collagen synthesis, smooth fine lines, and restore absolute skin vitality while you sleep.',
    ingredients: ['Aqua', 'Squalane', 'Palmitoyl Tripeptide-1', 'Palmitoyl Tetrapeptide-7', 'Resveratrol', 'Niacinamide', 'Coenzyme Q10'],
    skinConcerns: ['anti-aging', 'firming', 'repair'],
    applicationRitual: 'Gently massage onto clean face, neck, and décolleté every evening.',
    rating: 4.9,
    reviewsCount: 158,
    isBestSeller: true,
    collection: 'L’Élixir de Jeunesse',
    badge: 'Award Winner'
  },
  {
    id: 'moonlight-recovery',
    name: 'Moonlight Recovery Balm',
    tagline: 'Nourishing night treatment balm for radiant, resilient skin.',
    category: 'night-creams',
    emoji: '✨',
    price: 210,
    volume: '75 ml ℮ 2.5 FL. OZ.',
    concentration: 'Night Treatment Balm',
    description: 'An indulgent, rich night recovery balm that melts into a silky treatment oil on contact. Combines cold-pressed evening primrose oil, prickly pear seed oil, and calming lavender to help you wake up with deeply radiant skin.',
    ingredients: ['Opuntia Ficus-Indica Seed Oil', 'Oenothera Biennis Oil', 'Simmondsia Chinensis Seed Oil', 'Lavandula Angustifolia Oil'],
    skinConcerns: ['radiance', 'deep nourishment', 'dullness'],
    applicationRitual: 'Massage a small pea-sized amount onto dry or slightly damp skin as the final step.',
    rating: 5.0,
    reviewsCount: 64,
    collection: 'L’Élixir de Jeunesse',
    badge: 'Highly Rated'
  },
  {
    id: 'cellular-repair-elixir',
    name: 'Cellular Repair Night Elixir',
    tagline: 'Highly concentrated active formula restoring absolute skin vitality.',
    category: 'night-creams',
    emoji: '🌌',
    price: 225,
    volume: '50 ml ℮ 1.7 FL. OZ.',
    concentration: 'Intensive Night Elixir',
    description: 'Designed to target deep wrinkles and skin relaxation. This overnight luxury elixir is supercharged with copper peptides, plant-derived growth factors, and marine algae to encourage intense skin self-renewal.',
    ingredients: ['Aqua', 'Glycerin', 'Copper Tripeptide-1', 'Algae Extract', 'Centella Asiatica Extract', 'Adenosine'],
    skinConcerns: ['wrinkles', 'loss of firmness'],
    applicationRitual: 'Apply a few drops to your face before sleeping. Follow with your heavy cream.',
    rating: 4.9,
    reviewsCount: 51,
    collection: 'L’Élixir de Jeunesse'
  },
  {
    id: 'retinol-overnight',
    name: 'Bio-Active Retinol Overnight',
    tagline: 'Micro-encapsulated retinol to smooth texture and firm contours.',
    category: 'night-creams',
    emoji: '🔮',
    price: 195,
    volume: '50 ml ℮ 1.7 FL. OZ.',
    concentration: 'Retinol Cream',
    description: 'Formulated with advanced 1% encapsulated retinol which releases gradually overnight to minimize irritation. Accelerates cellular turnover to dramatically smooth skin texture and improve skin firmness.',
    ingredients: ['Aqua', 'Caprylic/Capric Triglyceride', 'Retinol', 'Phospholipids', 'Ceramide NP', 'Allantoin'],
    skinConcerns: ['fine lines', 'uneven texture'],
    applicationRitual: 'Apply a pea-sized amount to completely dry skin at night. Start with twice a week.',
    rating: 4.8,
    reviewsCount: 82,
    collection: 'L’Élixir de Jeunesse'
  },
  {
    id: 'divine-royal-cream',
    name: 'Divine Royal Nourishing Cream',
    tagline: 'Decadent nighttime treatment utilizing rare botanical royal jelly.',
    category: 'night-creams',
    emoji: '👑',
    price: 250,
    volume: '60 ml ℮ 2.0 FL. OZ.',
    concentration: 'Luxury Night Cream',
    description: 'Our most opulent night treatment cream. Divine Royal infuses active royal jelly, cold-pressed macadamia nut oil, and white honey to deeply feed damaged, depleted skin, restoring an unparalleled youthful suppleness.',
    ingredients: ['Aqua', 'Royal Jelly', 'Macadamia Ternifolia Seed Oil', 'Honey Extract', 'Tocopherol', 'Beta-Glucan'],
    skinConcerns: ['extreme dryness', 'elasticity', 'cellular depletion'],
    applicationRitual: 'Gently warm in palms and press over face, neck, and neck area.',
    rating: 5.0,
    reviewsCount: 44,
    collection: 'L’Élixir de Jeunesse'
  },

  // --- Category 4: Day Creams (day-creams) ---
  {
    id: 'ultra-shield-day',
    name: 'Ultra Shield Day Protection',
    tagline: 'Antioxidant-rich protection to defend skin against daytime stress.',
    category: 'day-creams',
    emoji: '☀️',
    price: 115,
    volume: '50 ml ℮ 1.7 FL. OZ.',
    concentration: 'Antioxidant Day Cream',
    description: 'A light, protective cream that defends the skin from daily oxidative stressors. Infused with vitamin E, coenzyme Q10, and pine bark extract, it leaves a satin, makeup-ready finish.',
    ingredients: ['Aqua', 'Squalane', 'Pinus Pinaster Bark Extract', 'Ubiquinone', 'Tocopherol', 'Panthenol'],
    skinConcerns: ['anti-pollution', 'hydration'],
    applicationRitual: 'Massage onto clean face and neck every morning as your final hydration step.',
    rating: 4.8,
    reviewsCount: 93,
    collection: 'L’Élixir de Jeunesse'
  },
  {
    id: 'radiant-spf-fluid',
    name: 'Radiant SPF 30 Day Fluid',
    tagline: 'Luminous solar protection infused with pure green tea extracts.',
    category: 'day-creams',
    emoji: '🛡️',
    price: 105,
    volume: '50 ml ℮ 1.7 FL. OZ.',
    concentration: 'Broad Spectrum SPF 30',
    description: 'A luxurious mineral sunscreen fluid that leaves no white cast. Provides broad-spectrum UV defense while infusing skin with calming green tea, antioxidant vitamin C, and zinc oxide.',
    ingredients: ['Zinc Oxide', 'Aqua', 'Caprylic/Capric Triglyceride', 'Camellia Sinensis Leaf Extract', 'Tetrahexyldecyl Ascorbate'],
    skinConcerns: ['sun defense', 'radiance'],
    applicationRitual: 'Apply generously to face and neck 15 minutes before sun exposure.',
    rating: 4.7,
    reviewsCount: 119,
    collection: 'L’Élixir de Jeunesse'
  },
  {
    id: 'anti-pollution-cream',
    name: 'Anti-Pollution Ozone Cream',
    tagline: 'Advanced shield defending urban skin against microscopic pollution.',
    category: 'day-creams',
    emoji: '☁️',
    price: 125,
    volume: '50 ml ℮ 1.7 FL. OZ.',
    concentration: 'Urban Shield Cream',
    description: 'Designed specifically for city dwellers. This cream creates a breathable microscopic barrier that blocks smoke, exhaust, and heavy metals from adhering to and damaging your skin barrier.',
    ingredients: ['Aqua', 'Biosaccharide Gum-4', 'Moringa Oleifera Seed Extract', 'Niacinamide', 'Alteromonas Ferment Extract'],
    skinConcerns: ['pollution shield', 'clogged pores'],
    applicationRitual: 'Apply morning after cleansing to lock in protective shielding.',
    rating: 4.8,
    reviewsCount: 67,
    collection: 'L’Élixir de Jeunesse'
  },
  {
    id: 'collagen-day-infusion',
    name: 'Collagen Boosting Day Infusion',
    tagline: 'Daily marine collagen-infused cream for a bouncy, youthful look.',
    category: 'day-creams',
    emoji: '🧬',
    price: 140,
    volume: '50 ml ℮ 1.7 FL. OZ.',
    concentration: 'Collagen Day Cream',
    description: 'A firming, lifting day cream that targets loss of structure. Hydrated marine collagen and elastic peptides rebuild skin bounce, giving an instant plumping effect to lines and dry contours.',
    ingredients: ['Aqua', 'Soluble Collagen', 'Hydrolyzed Elastin', 'Palmitoyl Tripeptide-5', 'Sodium Hyaluronate'],
    skinConcerns: ['loss of firmness', 'fine lines'],
    applicationRitual: 'Massage upwards on jawline, cheeks, and forehead in the morning.',
    rating: 4.9,
    reviewsCount: 88,
    collection: 'L’Élixir de Jeunesse'
  },
  {
    id: 'aqua-gel-veil',
    name: 'Aqua-Gel Hydrating Veil',
    tagline: 'A cooling, ultra-fresh morning moisturizer that hydrates instantly.',
    category: 'day-creams',
    emoji: '🌊',
    price: 90,
    volume: '50 ml ℮ 1.7 FL. OZ.',
    concentration: 'Gel-Moisturizer',
    description: 'A refreshing, weightless gel-cream that bursts into a watery cooling veil upon skin contact. Powered by hyaluronic acid, organic aloe, and refreshing glacier water, it keeps skin hydrated for 24 hours.',
    ingredients: ['Aqua', 'Aloe Barbadensis Leaf Juice', 'Sodium Hyaluronate', 'Glycerin', 'Saccharide Isomerate'],
    skinConcerns: ['oiliness', 'extreme dehydration'],
    applicationRitual: 'Smooth generously over face as an ultra-light makeup base.',
    rating: 4.8,
    reviewsCount: 145,
    collection: 'L’Élixir de Jeunesse'
  },

  // --- Category 5: Facial Cleansers (facial-cleansers) ---
  {
    id: 'crystal-foam',
    name: 'Crystal Foam Cleanser',
    tagline: 'A gentle, oxygenating foaming cleanser for clean, balanced skin.',
    category: 'facial-cleansers',
    emoji: '🫧',
    price: 78,
    volume: '150 ml ℮ 5.1 FL. OZ.',
    concentration: 'Foaming Facial Cleanser',
    description: 'Crystal Foam Cleanser lifts away urban micro-particles, makeup, and oil without drying or stripping. Botanical amino acids and rose water create a cloud-like lather to leave skin soft, calm, and perfectly fresh.',
    ingredients: ['Aqua', 'Rosa Centifolia Flower Water', 'Sodium Cocoyl Glutamate', 'Glycerin', 'Aloe Barbadensis Leaf Juice', 'Allantoin'],
    skinConcerns: ['cleansing', 'pores', 'makeup removal'],
    applicationRitual: 'Pump foam into damp palms. Massage in gentle circular motions over the face, then rinse thoroughly.',
    rating: 4.8,
    reviewsCount: 122,
    collection: 'Le Rituel Purifiant',
    badge: 'Gentle Formula'
  },
  {
    id: 'oxygenating-milk',
    name: 'Oxygenating Milk Wash',
    tagline: 'Creamy botanical cleansing milk that dissolves impurities gently.',
    category: 'facial-cleansers',
    emoji: '🥛',
    price: 65,
    volume: '120 ml ℮ 4.1 FL. OZ.',
    concentration: 'Cleansing Milk',
    description: 'This ultra-soothing, creamy cleansing milk effortlessly sweeps away makeup, sunscreens, and pollution particles. Enriched with thermal waters, oat lipids, and calendula extracts to protect the skin lipid barrier.',
    ingredients: ['Aqua', 'Caprylic/Capric Triglyceride', 'Avena Sativa Kernel Oil', 'Calendula Officinalis Extract', 'Squalane'],
    skinConcerns: ['dryness', 'makeup removal', 'sensitivity'],
    applicationRitual: 'Massage onto dry skin, then wipe clean with a warm, damp face cloth.',
    rating: 4.7,
    reviewsCount: 94,
    collection: 'Le Rituel Purifiant'
  },
  {
    id: 'pure-balance-gel',
    name: 'Pure Balance Gel Purifier',
    tagline: 'Clarifying oil-control cleanser with alpine willowherb.',
    category: 'facial-cleansers',
    emoji: '🧪',
    price: 70,
    volume: '150 ml ℮ 5.1 FL. OZ.',
    concentration: 'Purifying Gel Wash',
    description: 'An advanced, non-stripping gel cleanser designed for combination and oily skin types. Alpine willowherb regulate excess sebum, while natural salicylic acid gently clears debris from within pores.',
    ingredients: ['Aqua', 'Decyl Glucoside', 'Epilobium Fleischeri Extract', 'Salicylic Acid', 'Glycerin', 'Panthenol'],
    skinConcerns: ['oil control', 'clogged pores', 'blemishes'],
    applicationRitual: 'Massage onto damp face to generate a soft foam. Rinse thoroughly with lukewarm water.',
    rating: 4.6,
    reviewsCount: 76,
    collection: 'Le Rituel Purifiant'
  },
  {
    id: 'rosewater-balm',
    name: 'Rosewater Cleansing Balm',
    tagline: 'Rich balm transforming into milk to dissolve water-resistant makeup.',
    category: 'facial-cleansers',
    emoji: '🌹',
    price: 85,
    volume: '100 ml ℮ 3.4 FL. OZ.',
    concentration: 'Deep Cleansing Balm',
    description: 'A decadent sorbet-textured balm that transforms into a silky cleansing oil, then a milky emulsion. Easily breaks down water-resistant makeup, waterproof mascara, and pollutants while intensely nourishing skin.',
    ingredients: ['Ethylhexyl Palmitate', 'Rosa Damascena Flower Oil', 'Prunus Amygdalus Dulcis Oil', 'Tocopheryl Acetate'],
    skinConcerns: ['stubborn makeup', 'extreme dryness', 'dehydration'],
    applicationRitual: 'Massage a small scoop onto dry face. Emulsify with warm water, then rinse off.',
    rating: 4.9,
    reviewsCount: 143,
    collection: 'Le Rituel Purifiant'
  },
  {
    id: 'intense-clarifying',
    name: 'Intense Clarifying Foaming Gel',
    tagline: 'Active alpha-hydroxy acid cleanser to gently brighten and refine.',
    category: 'facial-cleansers',
    emoji: '💎',
    price: 75,
    volume: '120 ml ℮ 4.1 FL. OZ.',
    concentration: 'Exfoliating Cleanser',
    description: 'Supercharged with organic fruit acids (AHAs), this foaming cleanser micro-exfoliates dead cells, sweeps away daily congestion, and reveals a beautifully smooth, luminous complexion over time.',
    ingredients: ['Aqua', 'Lactic Acid', 'Glycolic Acid', 'Sodium Cocoyl Isethionate', 'Vaccinium Myrtillus Fruit Extract'],
    skinConcerns: ['dullness', 'uneven texture', 'dark spots'],
    applicationRitual: 'Use every second evening. Massage on damp face, leave for 30 seconds, then rinse.',
    rating: 4.8,
    reviewsCount: 81,
    collection: 'Le Rituel Purifiant'
  },

  // --- Category 6: Body Cleansers (body-cleansers) ---
  {
    id: 'satin-rose-wash',
    name: 'Satin Rose Body Wash',
    tagline: 'Delicately scented bath wash that nourishes skin with rose seed oil.',
    category: 'body-cleansers',
    emoji: '🛁',
    price: 60,
    volume: '250 ml ℮ 8.4 FL. OZ.',
    concentration: 'Luxurious Body Wash',
    description: 'A high-end foaming wash infused with pure Damascena rosewater and cold-pressed rosehip seed oil. Cleanses the body while maintaining a gorgeous satin moisture layer and leaving a delicate floral fragrance.',
    ingredients: ['Aqua', 'Rosa Damascena Flower Water', 'Rosa Canina Seed Oil', 'Glycerin', 'Sodium Lauroyl Methyl Isethionate'],
    skinConcerns: ['dry skin', 'scent layering'],
    applicationRitual: 'Smooth onto damp skin, lather beautifully, then rinse. Perfect for the bath or shower.',
    rating: 4.9,
    reviewsCount: 110,
    collection: 'Le Rituel Purifiant'
  },
  {
    id: 'santal-cleansing-oil',
    name: 'Santal Cream Cleansing Oil',
    tagline: 'Luxury lipid-replenishing body wash featuring warm sandalwood.',
    category: 'body-cleansers',
    emoji: '🧴',
    price: 75,
    volume: '200 ml ℮ 6.7 FL. OZ.',
    concentration: 'Cleansing Oil-To-Foam',
    description: 'An indulgent shower oil that transforms into a creamy foam upon contact with water. Packed with organic sweet almond oil and warm Mysore sandalwood oil to protect, soften, and perfume your body.',
    ingredients: ['MIPA-Laureth Sulfate', 'Prunus Amygdalus Dulcis Oil', 'Santalum Album Wood Oil', 'Laureth-3', 'Tocopherol'],
    skinConcerns: ['extreme body dryness', 'sensitive skin'],
    applicationRitual: 'Apply directly to wet body, massage to create a milky wash, then rinse off.',
    rating: 4.9,
    reviewsCount: 95,
    collection: 'Le Rituel Purifiant'
  },
  {
    id: 'eucalyptus-gel',
    name: 'Revitalizing Eucalyptus Gel',
    tagline: 'Invigorating cooling cleanser to refresh both skin and spirit.',
    category: 'body-cleansers',
    emoji: '🌿',
    price: 55,
    volume: '250 ml ℮ 8.4 FL. OZ.',
    concentration: 'Aromatherapy Body Wash',
    description: 'Formulated with organic eucalyptus, Siberian pine, and wild mint essential oils. This energizing wash stimulates systemic circulation, relieves muscle tension, and leaves you beautifully clean and mentally alert.',
    ingredients: ['Aqua', 'Eucalyptus Globulus Leaf Oil', 'Mentha Arvensis Leaf Oil', 'Aloe Barbadensis Leaf Extract'],
    skinConcerns: ['fatigue', 'sluggishness'],
    applicationRitual: 'Use in morning showers. Inhale the refreshing steam deeply.',
    rating: 4.8,
    reviewsCount: 64,
    collection: 'Le Rituel Purifiant'
  },
  {
    id: 'citrus-bath-nectar',
    name: 'Citrus Velvet Bath Nectar',
    tagline: 'Fizzy nectar foaming oil rich in vitamin C and sweet orange essence.',
    category: 'body-cleansers',
    emoji: '🍊',
    price: 65,
    volume: '200 ml ℮ 6.7 FL. OZ.',
    concentration: 'Luxury Bath Oil',
    description: 'An aromatic nectar designed for luxury soaking. Rich in sun-warmed orange blossom, wild grapefruit extract, and softening apricot kernel oil, it infuses the bathwater with a velvety hydrating foam.',
    ingredients: ['Aqua', 'Citrus Aurantium Dulcis Peel Oil', 'Prunus Armeniaca Kernel Oil', 'Ascorbic Acid'],
    skinConcerns: ['dull body skin', 'dehydration'],
    applicationRitual: 'Pour 2-3 capfuls directly under running bathwater. Swirl to create a rich lather.',
    rating: 4.7,
    reviewsCount: 38,
    collection: 'Le Rituel Purifiant'
  },
  {
    id: 'pure-coconut-wash',
    name: 'Pure Coconut Oil Body Wash',
    tagline: 'Extremely creamy virgin coconut oil wash for dry, sensitive body skin.',
    category: 'body-cleansers',
    emoji: '🥥',
    price: 50,
    volume: '250 ml ℮ 8.4 FL. OZ.',
    concentration: 'Ultra-Nourishing Wash',
    description: 'Formulated specifically for reactive skin. This soap-free body wash utilizes cold-pressed virgin coconut lipids to gently clear impurities without stripping the skin of its crucial protective sebum.',
    ingredients: ['Aqua', 'Cocos Nucifera Oil', 'Glycerin', 'Lauryl Glucoside', 'Sodium Cocoyl Isethionate'],
    skinConcerns: ['dry flaky skin', 'irritation', 'barrier damage'],
    applicationRitual: 'Apply generously to body using hands or a soft washcloth. Rinse with lukewarm water.',
    rating: 4.8,
    reviewsCount: 42,
    collection: 'Le Rituel Purifiant'
  },

  // --- Category 7: Gentle Cleansers (gentle-cleansers) ---
  {
    id: 'botanical-fresh',
    name: 'Botanical Fresh Cleanser',
    tagline: 'A refreshing, balancing cleanser packed with organic botanicals.',
    category: 'gentle-cleansers',
    emoji: '🌿',
    price: 72,
    volume: '120 ml ℮ 4.1 FL. OZ.',
    concentration: 'Refreshing Gel Cleanser',
    description: 'A lightweight gel cleanser infused with rosemary, mint, and green tea extracts. Gently purifies the skin while preserving the natural lipid barrier, leaving a crisp botanical freshness.',
    ingredients: ['Aqua', 'Rosmarinus Officinalis Extract', 'Mentha Piperita Leaf Extract', 'Camellia Sinensis Extract', 'Glycerin'],
    skinConcerns: ['cleansing', 'oiliness', 'refreshing'],
    applicationRitual: 'Lather gel with water and massage over face. Rinse thoroughly. Ideal for your morning refresh.',
    rating: 4.7,
    reviewsCount: 89,
    collection: 'Le Rituel Purifiant'
  },
  {
    id: 'chamomile-infusion',
    name: 'Calming Chamomile Infusion',
    tagline: 'Extra-sensitive face cleanser utilizing pure Roman chamomile.',
    category: 'gentle-cleansers',
    emoji: '🌼',
    price: 68,
    volume: '150 ml ℮ 5.1 FL. OZ.',
    concentration: 'Soothing Cleansing Water',
    description: 'Designed for highly reactive, easily flushed skin. Roman chamomile and organic cornflower waters instantly soothe tight or burning sensations while removing superficial impurities.',
    ingredients: ['Chamomilla Recutita Flower Water', 'Centaurea Cyanus Flower Water', 'Glycerin', 'Decyl Glucoside'],
    skinConcerns: ['flushing', 'extreme sensitivity', 'redness'],
    applicationRitual: 'Saturate a soft organic cotton pad and sweep across face. No rinsing required.',
    rating: 4.8,
    reviewsCount: 71,
    collection: 'Le Rituel Purifiant'
  },
  {
    id: 'delicate-oat-milk',
    name: 'Delicate Oat Milk Cleanser',
    tagline: 'Soothing lipid-balancing wash ideal for irritated or dry skin.',
    category: 'gentle-cleansers',
    emoji: '🌾',
    price: 74,
    volume: '150 ml ℮ 5.1 FL. OZ.',
    concentration: 'Gentle Cleansing Cream',
    description: 'A velvety, non-foaming cream cleanser containing micro-fine oat colloidal lipids and botanical squalane. It melts into the skin to extract sebum and dirt while coating dry skin in protective hydration.',
    ingredients: ['Aqua', 'Colloidal Oatmeal Extract', 'Squalane', 'Glycerin', 'Allantoin', 'Centella Asiatica'],
    skinConcerns: ['dryness', 'irritation', 'barrier recovery'],
    applicationRitual: 'Massage onto damp skin. Rinse off with tepid water or wipe off with damp cotton.',
    rating: 4.9,
    reviewsCount: 104,
    collection: 'Le Rituel Purifiant'
  },
  {
    id: 'sensitive-soapless',
    name: 'Sensitive Skin Soapless Gel',
    tagline: 'Ultra-pure soap-free cleansing gel for reactive skin barriers.',
    category: 'gentle-cleansers',
    emoji: '🛡️',
    price: 70,
    volume: '120 ml ℮ 4.1 FL. OZ.',
    concentration: 'Soap-Free Gel Wash',
    description: 'Formulated with only 10 essential ingredients to prevent any risk of allergic reaction. This ultra-gentle, non-foaming gel respects the physiological pH of sensitive skin.',
    ingredients: ['Aqua', 'Glycerin', 'Lauryl Glucoside', 'Sodium Hyaluronate', 'Citric Acid', 'Xanthan Gum'],
    skinConcerns: ['allergic reactions', 'extreme sensitivity'],
    applicationRitual: 'Smooth onto wet face, massage gently, then rinse with cool water.',
    rating: 4.7,
    reviewsCount: 52,
    collection: 'Le Rituel Purifiant'
  },
  {
    id: 'probiotic-soothing',
    name: 'Probiotic Soothing Cleansing Water',
    tagline: 'Micellar water packed with skin-friendly bacterial ferments.',
    category: 'gentle-cleansers',
    emoji: '💧',
    price: 80,
    volume: '200 ml ℮ 6.7 FL. OZ.',
    concentration: 'Probiotic Micellar Water',
    description: 'This rinse-free cleanser uses micellar technology to collect surface impurities while deploying active lactobacillus ferments to balance the skin microflora and boost immune defenses.',
    ingredients: ['Aqua', 'Lactobacillus Ferment Lysate', 'Poloxamer 184', 'Sodium PCA', 'Zinc PCA'],
    skinConcerns: ['acne-prone', 'unbalanced skin', 'redness'],
    applicationRitual: 'Apply morning and night using a clean cotton pad. No rinse necessary.',
    rating: 4.8,
    reviewsCount: 63,
    collection: 'Le Rituel Purifiant'
  },

  // --- Category 8: Facial Scrubs (facial-scrubs) ---
  {
    id: 'rose-quartz-scrub',
    name: 'Rose Quartz Facial Scrub',
    tagline: 'Gentle rose quartz powder exfoliation for a luminous complexion.',
    category: 'facial-scrubs',
    emoji: '🍃',
    price: 88,
    volume: '100 ml ℮ 3.4 FL. OZ.',
    concentration: 'Gentle Exfoliator',
    description: 'Infused with micro-fine rose quartz crystals and organic fruit enzymes, this ultra-gentle scrub buffs away dull surface cells to reveal healthy, glowing skin without causing irritation.',
    ingredients: ['Aqua', 'Rose Quartz Powder', 'Papain Enzyme', 'Simmondsia Chinensis Wax Esters', 'Glycerin'],
    skinConcerns: ['dullness', 'texture refinement', 'radiance'],
    applicationRitual: 'Massage onto damp skin using light, circular pressure twice a week. Rinse thoroughly.',
    rating: 4.8,
    reviewsCount: 105,
    isNew: true,
    collection: 'Le Rituel Purifiant',
    badge: 'New'
  },
  {
    id: 'bamboo-polish',
    name: 'Bamboo Micro-Polish Scrub',
    tagline: 'Extremely fine bamboo silica powder to polish pores to perfection.',
    category: 'facial-scrubs',
    emoji: '🎋',
    price: 82,
    volume: '75 ml ℮ 2.5 FL. OZ.',
    concentration: 'Micro-Exfoliating Polish',
    description: 'Formulated with ultra-fine, rounded bamboo powder particles that sweep away dead cells, whiteheads, and flakiness. Bamboo silica stimulates cellular renewal, giving an instant satin finish.',
    ingredients: ['Aqua', 'Bambusa Arundinacea Stem Powder', 'Squalane', 'Glycerin', 'Panthenol'],
    skinConcerns: ['clogged pores', 'roughness', 'blackheads'],
    applicationRitual: 'Massage a pea-sized amount on wet nose, forehead, and chin. Rinse with cool water.',
    rating: 4.7,
    reviewsCount: 74,
    collection: 'Le Rituel Purifiant'
  },
  {
    id: 'glycolic-fruit',
    name: 'Glycolic Fruit Acid Polish',
    tagline: 'Double action mechanical and chemical fruit enzyme scrub.',
    category: 'facial-scrubs',
    emoji: '🍍',
    price: 95,
    volume: '75 ml ℮ 2.5 FL. OZ.',
    concentration: 'Active Peel Scrub',
    description: 'Combines mechanical jojoba spheres with chemical glycolic acid (AHA) and pineapple bromelain enzymes. This powerful triple-action treatment melts away cellular congestion to resurface your skin.',
    ingredients: ['Aqua', 'Glycolic Acid', 'Bromelain', 'Jojoba Esters', 'Niacinamide'],
    skinConcerns: ['dullness', 'pigmentation', 'scars'],
    applicationRitual: 'Apply a thin layer to clean face. Leave for 2 minutes, then massage lightly and rinse.',
    rating: 4.9,
    reviewsCount: 88,
    collection: 'Le Rituel Purifiant'
  },
  {
    id: 'apricot-pearl',
    name: 'Radiance Apricot Pearl Scrub',
    tagline: 'Crushed mother-of-pearl and apricot kernels for cellular activation.',
    category: 'facial-scrubs',
    emoji: '🍑',
    price: 78,
    volume: '100 ml ℮ 3.4 FL. OZ.',
    concentration: 'Cell-Activating Scrub',
    description: 'A luxurious physical scrub utilizing finely crushed mother-of-pearl and cold-pressed apricot kernel oil. Gently lifts flaky cells while depositing rich essential fatty acids to nourish the skin underneath.',
    ingredients: ['Aqua', 'Mother of Pearl Powder', 'Prunus Armeniaca Kernel Oil', 'Glycerin', 'Allantoin'],
    skinConcerns: ['dry skin', 'dullness'],
    applicationRitual: 'Gently massage over face twice a week. Rinse off with warm water.',
    rating: 4.8,
    reviewsCount: 56,
    collection: 'Le Rituel Purifiant'
  },
  {
    id: 'jojoba-bead',
    name: 'Ultra-Gentle Jojoba Bead Exfoliator',
    tagline: 'Biodegradable round jojoba wax spheres for delicate physical polish.',
    category: 'facial-scrubs',
    emoji: '🔮',
    price: 85,
    volume: '75 ml ℮ 2.5 FL. OZ.',
    concentration: 'Gentle Physical Polish',
    description: 'Designed specifically for sensitive skin types. Contains 100% spherical, soft jojoba wax beads that roll smoothly across the skin, polishing away cellular debris without causing micro-tears or redness.',
    ingredients: ['Aqua', 'Hydrogenated Jojoba Oil', 'Squalane', 'Aloe Barbadensis Leaf Extract', 'Panthenol'],
    skinConcerns: ['rough texture', 'extreme sensitivity'],
    applicationRitual: 'Massage gently over damp skin with small circular motions, then rinse.',
    rating: 4.7,
    reviewsCount: 49,
    collection: 'Le Rituel Purifiant'
  },

  // --- Category 9: Face Masks (face-masks) ---
  {
    id: 'bloom-hydration-mask',
    name: 'Bloom Hydration Mask',
    tagline: 'An intensive moisturizing facial mask for dehydrated, tired skin.',
    category: 'face-masks',
    emoji: '💆',
    price: 98,
    volume: '75 ml ℮ 2.5 FL. OZ.',
    concentration: 'Intensive Hydration Mask',
    description: 'A luxurious gel-cream mask that saturates the skin with hydration. Formulated with red algae extracts, hyaluronic acid, and botanical flower waters to plump, soothe, and revive skin.',
    ingredients: ['Aqua', 'Chondrus Crispus Extract', 'Sodium Hyaluronate', 'Calendula Officinalis Water', 'Glycerin', 'Panthenol'],
    skinConcerns: ['extreme dehydration', 'redness', 'fatigue'],
    applicationRitual: 'Apply a generous layer to face and neck. Leave for 15 minutes, then wipe clean.',
    rating: 4.9,
    reviewsCount: 118,
    collection: 'L’Élixir de Jeunesse'
  },
  {
    id: 'golden-night-mask',
    name: 'Golden Night Mask',
    tagline: 'Overnight luxury recovery mask for gold-standard radiance.',
    category: 'face-masks',
    emoji: '✨',
    price: 155,
    volume: '80 ml ℮ 2.7 FL. OZ.',
    concentration: 'Overnight Treatment Mask',
    description: 'Our most decadent overnight treatment. Golden Night Mask combines colloidal gold, royal jelly, and botanical oils to regenerate, firm, and intensely illuminate the complexion.',
    ingredients: ['Aqua', 'Colloidal Gold', 'Royal Jelly Extract', 'Argania Spinosa Kernel Oil', 'Niacinamide', 'Glycerin'],
    skinConcerns: ['anti-aging', 'radiance', 'loss of firmness'],
    applicationRitual: 'Smooth over face and neck as the final night step. Leave overnight.',
    rating: 5.0,
    reviewsCount: 176,
    isBestSeller: true,
    collection: 'L’Élixir de Jeunesse',
    badge: 'Signature'
  },
  {
    id: 'french-clay-mask',
    name: 'Purifying French Clay Mask',
    tagline: 'Deeply drawing green clay mask enriched with lavender oil.',
    category: 'face-masks',
    emoji: '🧱',
    price: 85,
    volume: '100 ml ℮ 3.4 FL. OZ.',
    concentration: 'Detoxifying Clay Mask',
    description: 'French green clay draws out deep-seated pore impurities, excess sebum, and heavy metals. Formulated with organic lavender, rosemary essential oils, and thermal water to purify without cracking or over-drying.',
    ingredients: ['Montmorillonite (Green Clay)', 'Aqua', 'Lavandula Angustifolia Oil', 'Rosmarinus Officinalis Oil'],
    skinConcerns: ['clogged pores', 'oiliness', 'impurities'],
    applicationRitual: 'Apply a smooth layer, avoiding eye area. Let dry for 10 minutes, then rinse with warm water.',
    rating: 4.8,
    reviewsCount: 92,
    collection: 'Le Rituel Purifiant'
  },
  {
    id: 'cellular-glow-sheet',
    name: 'Cellular Glow Sheet Mask Set',
    tagline: 'Pure biocellulose sheet masks soaked in concentrated hyaluronic acid.',
    category: 'face-masks',
    emoji: '📝',
    price: 90,
    volume: '5 pack ℮ 5 x 25 ml',
    concentration: 'Treatment Sheet Masks',
    description: 'An express facial treatment. These premium, biodegradable coconut-derived biocellulose sheets fit like a second skin, infusing active peptides, vitamin B5, and double-molecular hyaluronic acid deep into the epidermis.',
    ingredients: ['Aqua', 'Sodium Hyaluronate', 'Panthenol', 'Niacinamide', 'Centella Asiatica'],
    skinConcerns: ['dehydration', 'dullness', 'redness'],
    applicationRitual: 'Unfold mask and apply to face. Leave on for 20 minutes, then discard and tap remaining serum in.',
    rating: 4.9,
    reviewsCount: 68,
    collection: 'L’Élixir de Jeunesse'
  },
  {
    id: 'vitamin-c-mask',
    name: 'Oxygenating Vitamin C Mask',
    tagline: 'Bubbling vitamin C cream mask that banishes dullness instantly.',
    category: 'face-masks',
    emoji: '🍊',
    price: 110,
    volume: '75 ml ℮ 2.5 FL. OZ.',
    concentration: 'Brightening Mask',
    description: 'A spectacular treatment that self-foams into micro-bubbles of pure oxygen on your skin. Deploys stable vitamin C and wild rosehip oil to clarify dark spots, reverse sun damage, and boost radiance in 5 minutes.',
    ingredients: ['Aqua', 'Methyl Perfluorobutyl Ether', 'Ascorbyl Glucoside', 'Rosa Canina Fruit Oil', 'Glycerin'],
    skinConcerns: ['dullness', 'fatigue', 'pigmentation'],
    applicationRitual: 'Apply a thin layer to clean dry skin. Watch it bubble up! Massage gently and rinse off after 5 minutes.',
    rating: 4.9,
    reviewsCount: 57,
    collection: 'L’Élixir de Jeunesse'
  }
];

export const REVIEWS: Review[] = [
  {
    id: 'r1',
    author: 'Lady Genevieve W.',
    rating: 5,
    date: 'June 18, 2026',
    title: 'The epitome of pure elegance',
    content: 'Rose Élégante is nothing short of a masterpiece. The trail is hypnotic, garnering compliments wherever I travel. It possesses a velvety, high-end quality that lasts from early dawn into midnight. A permanent fixture on my vanity.',
    location: 'London, United Kingdom',
    verified: true,
    skinProfile: 'Fragrance Connoisseur'
  },
  {
    id: 'r2',
    author: 'Dr. Evelyn S.',
    rating: 5,
    date: 'May 24, 2026',
    title: 'Exceptional skin barrier repair',
    content: 'As a dermatologist, I am notoriously selective with ingredients. Silk Glow Moisturizer has surpassed my highest expectations. The inclusion of hydrolyzed silk and squalane provides exceptional epidermal defense without any heavy occlusion. Timeless and outstanding.',
    location: 'New York, USA',
    verified: true,
    skinProfile: 'Dry, Sensitive Skin'
  },
  {
    id: 'r3',
    author: 'Aiko M.',
    rating: 5,
    date: 'April 12, 2026',
    title: 'My nightly meditation ritual',
    content: 'The Moonlight Recovery Balm nighttime oil has transformed my oily-dehydrated skin. I wake up with a soft, natural radiance that feels balanced and firm. The soft scent of lavender and botanicals is a wonderful bedtime meditation.',
    location: 'Tokyo, Japan',
    verified: true,
    skinProfile: 'Oily, Dehydrated Skin'
  },
  {
    id: 'r4',
    author: 'Victoire de R.',
    rating: 5,
    date: 'March 05, 2026',
    title: 'Warm, majestic, comforting',
    content: 'Santal Précieux is a creamy cloud of gorgeous Mysore Sandalwood. It wraps around you like a heavy, luxurious cashmere scarf on an autumn stroll along the Seine. It is woody, soft, gender-neutral, and beautifully complex.',
    location: 'Paris, France',
    verified: true,
    skinProfile: 'Signature Scent'
  }
];

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    question: 'How does your skin feel in the afternoon hours?',
    options: [
      { text: 'Tight, flaky, or requiring continuous hydration', value: 'dry' },
      { text: 'Slightly oily in the T-zone but normal elsewhere', value: 'combination' },
      { text: 'Dull, tired, and in need of deep restoration', value: 'aging' },
      { text: 'Perfectly balanced but occasionally sensitive', value: 'normal' }
    ]
  },
  {
    id: 2,
    question: 'What is your primary aesthetic desire for your skin?',
    options: [
      { text: 'Unlocking a glass-like radiance and vibrant glow', value: 'radiance' },
      { text: 'Combating structural fine lines and restoring volume', value: 'anti-aging' },
      { text: 'Deeply purifying impurities while maintaining soft balance', value: 'cleansing' },
      { text: 'Soothing sensitive redness and establishing deep hydration', value: 'hydration' }
    ]
  },
  {
    id: 3,
    question: 'In olfactory expressions, which family calls to your soul?',
    options: [
      { text: 'Velvety, dew-kissed florals and fresh rose gardens', value: 'rose' },
      { text: 'Warm, exotic, creamy woods and deep amber trails', value: 'sandalwood' },
      { text: 'Bright, citrus-splashed coasts and sun-warmed absolute jasmine', value: 'jasmine' },
      { text: 'Calm, soothing herbaceous lavender and botanical fields', value: 'lavender' }
    ]
  },
  {
    id: 4,
    question: 'Which environment best describes your daily habitat?',
    options: [
      { text: 'Arid climate or indoor climate-controlled offices', value: 'indoor' },
      { text: 'High-density, polluted urban metropolis', value: 'urban' },
      { text: 'Temperate climate with seasonal weather shifts', value: 'temperate' }
    ]
  }
];
